export const Populars = [
  {
    id: 1,
    image: 'https://source.unsplash.com/random/400x300?sig=1',
    price: 20,
    discounted: true,
    discount: 0,
    isPopular: true,
  },
  {
    id: 2,
    image: 'https://source.unsplash.com/random/400x300?sig=2',
    price: 30,
    discounted: false,
    discount: 10,
    isPopular: false,
  },
]

export const Data = [
  {
    id: 1,
    image: 'https://source.unsplash.com/random/400x300?sig=1',
    price: 20,
    discounted: true,
    discount: 0,
    isPopular: true,
  },
  {
    id: 2,
    image: 'https://source.unsplash.com/random/400x300?sig=2',
    price: 30,
    discounted: false,
    discount: 10,
    isPopular: false,
  },
  {
    id: 3,
    image: 'https://source.unsplash.com/random/400x300?sig=3',
    price: 25,
    discounted: true,
    discount: 5,
    isPopular: true,
  },
  {
    id: 4,
    image: 'https://source.unsplash.com/random/400x300?sig=4',
    price: 40,
    discounted: false,
    discount: 0,
    isPopular: false,
  },
  {
    id: 5,
    image: 'https://source.unsplash.com/random/400x300?sig=5',
    price: 35,
    discounted: true,
    discount: 15,
    isPopular: true,
  },
  {
    id: 6,
    image: 'https://source.unsplash.com/random/400x300?sig=6',
    price: 22,
    discounted: false,
    discount: 0,
    isPopular: false,
  },
  {
    id: 7,
    image: 'https://source.unsplash.com/random/400x300?sig=7',
    price: 27,
    discounted: true,
    discount: 8,
    isPopular: true,
  },
  {
    id: 8,
    image: 'https://source.unsplash.com/random/400x300?sig=8',
    price: 33,
    discounted: false,
    discount: 0,
    isPopular: false,
  },
  {
    id: 9,
    image: 'https://source.unsplash.com/random/400x300?sig=9',
    price: 29,
    discounted: true,
    discount: 12,
    isPopular: true,
  },
  {
    id: 10,
    image: 'https://source.unsplash.com/random/400x300?sig=10',
    price: 37,
    discounted: false,
    discount: 0,
    isPopular: false,
  },
  {
    id: 11,
    image: 'https://source.unsplash.com/random/400x300?sig=11',
    price: 24,
    discounted: true,
    discount: 3,
    isPopular: true,
  },
  {
    id: 12,
    image: 'https://source.unsplash.com/random/400x300?sig=12',
    price: 31,
    discounted: false,
    discount: 0,
    isPopular: false,
  },
  {
    id: 13,
    image: 'https://source.unsplash.com/random/400x300?sig=13',
    price: 28,
    discounted: true,
    discount: 7,
    isPopular: true,
  },
  {
    id: 14,
    image: 'https://source.unsplash.com/random/400x300?sig=14',
    price: 38,
    discounted: false,
    discount: 0,
    isPopular: false,
  },
  {
    id: 15,
    image: 'https://source.unsplash.com/random/400x300?sig=15',
    price: 36,
    discounted: true,
    discount: 20,
    isPopular: true,
  },
  {
    id: 16,
    image: 'https://source.unsplash.com/random/400x300?sig=16',
    price: 21,
    discounted: false,
    discount: 0,
    isPopular: false,
  },
  {
    id: 17,
    image: 'https://source.unsplash.com/random/400x300?sig=17',
    price: 32,
    discounted: true,
    discount: 9,
    isPopular: true,
  },
  {
    id: 18,
    image: 'https://source.unsplash.com/random/400x300?sig=18',
    price: 26,
    discounted: false,
    discount: 0,
    isPopular: false,
  },
  {
    id: 19,
    image: 'https://source.unsplash.com/random/400x300?sig=19',
    price: 39,
    discounted: true,
    discount: 25,
    isPopular: true,
  },
  {
    id: 20,
    image: 'https://source.unsplash.com/random/400x300?sig=20',
    price: 23,
    discounted: false,
    discount: 0,
    isPopular: false,
  },
  {
    id: 21,
    image: 'https://source.unsplash.com/random/400x300?sig=21',
    price: 34,
    discounted: true,
    discount: 6,
    isPopular: true,
  },
  {
    id: 22,
    image: 'https://source.unsplash.com/random/400x300?sig=22',
    price: 41,
    discounted: false,
    discount: 0,
    isPopular: false,
  },
  {
    id: 23,
    image: 'https://source.unsplash.com/random/400x300?sig=23',
    price: 43,
    discounted: true,
    discount: 18,
    isPopular: true,
  },
  {
    id: 24,
    image: 'https://source.unsplash.com/random/400x300?sig=24',
    price: 45,
    discounted: false,
    discount: 0,
    isPopular: false,
  },
  {
    id: 25,
    image: 'https://source.unsplash.com/random/400x300?sig=25',
    price: 49,
    discounted: true,
    discount: 30,
    isPopular: true,
  },
  {
    id: 26,
    image: 'https://source.unsplash.com/random/400x300?sig=26',
    price: 42,
    discounted: false,
    discount: 0,
    isPopular: false,
  },
  {
    id: 27,
    image: 'https://source.unsplash.com/random/400x300?sig=27',
    price: 47,
    discounted: true,
    discount: 22,
    isPopular: true,
  },
  {
    id: 28,
    image: 'https://source.unsplash.com/random/400x300?sig=28',
    price: 44,
    discounted: false,
    discount: 0,
    isPopular: false,
  },
  {
    id: 29,
    image: 'https://source.unsplash.com/random/400x300?sig=29',
    price: 50,
    discounted: true,
    discount: 35,
    isPopular: true,
  },
  {
    id: 30,
    image: 'https://source.unsplash.com/random/400x300?sig=30',
    price: 48,
    discounted: false,
    discount: 0,
    isPopular: false,
  },
  {
    id: 31,
    image: 'https://source.unsplash.com/random/400x300?sig=31',
    price: 46,
    discounted: true,
    discount: 28,
    isPopular: true,
  },
  {
    id: 32,
    image: 'https://source.unsplash.com/random/400x300?sig=32',
    price: 52,
    discounted: false,
    discount: 0,
    isPopular: false,
  },
  {
    id: 33,
    image: 'https://source.unsplash.com/random/400x300?sig=33',
    price: 54,
    discounted: true,
    discount: 40,
    isPopular: true,
  },
  {
    id: 34,
    image: 'https://source.unsplash.com/random/400x300?sig=34',
    price: 58,
    discounted: false,
    discount: 0,
    isPopular: false,
  },
  {
    id: 35,
    image: 'https://source.unsplash.com/random/400x300?sig=35',
    price: 60,
    discounted: true,
    discount: 45,
    isPopular: true,
  },
  {
    id: 36,
    image: 'https://source.unsplash.com/random/400x300?sig=36',
    price: 56,
    discounted: false,
    discount: 0,
    isPopular: false,
  },
  {
    id: 37,
    image: 'https://source.unsplash.com/random/400x300?sig=37',
    price: 62,
    discounted: true,
    discount: 50,
    isPopular: true,
  },
  {
    id: 38,
    image: 'https://source.unsplash.com/random/400x300?sig=38',
    price: 64,
    discounted: false,
    discount: 0,
    isPopular: false,
  },
  {
    id: 39,
    image: 'https://source.unsplash.com/random/400x300?sig=39',
    price: 68,
    discounted: true,
    discount: 60,
    isPopular: true,
  },
  {
    id: 40,
    image: 'https://source.unsplash.com/random/400x300?sig=40',
    price: 70,
    discounted: false,
    discount: 0,
    isPopular: false,
  },
  {
    id: 41,
    image: 'https://source.unsplash.com/random/400x300?sig=41',
    price: 72,
    discounted: true,
    discount: 65,
    isPopular: true,
  },
  {
    id: 42,
    image: 'https://source.unsplash.com/random/400x300?sig=42',
    price: 76,
    discounted: false,
    discount: 0,
    isPopular: false,
  },
  {
    id: 43,
    image: 'https://source.unsplash.com/random/400x300?sig=43',
    price: 78,
    discounted: true,
    discount: 70,
    isPopular: true,
  },
  {
    id: 44,
    image: 'https://source.unsplash.com/random/400x300?sig=44',
    price: 82,
    discounted: false,
    discount: 0,
    isPopular: false,
  },
  {
    id: 45,
    image: 'https://source.unsplash.com/random/400x300?sig=45',
    price: 84,
    discounted: true,
    discount: 75,
    isPopular: true,
  },
  {
    id: 46,
    image: 'https://source.unsplash.com/random/400x300?sig=46',
    price: 88,
    discounted: false,
    discount: 0,
    isPopular: false,
  },
  {
    id: 47,
    image: 'https://source.unsplash.com/random/400x300?sig=47',
    price: 92,
    discounted: true,
    discount: 80,
    isPopular: true,
  },
  {
    id: 48,
    image: 'https://source.unsplash.com/random/400x300?sig=48',
    price: 96,
    discounted: false,
    discount: 0,
    isPopular: false,
  },
  {
    id: 49,
    image: 'https://source.unsplash.com/random/400x300?sig=49',
    price: 100,
    discounted: true,
    discount: 85,
    isPopular: true,
  },
  {
    id: 50,
    image: 'https://source.unsplash.com/random/400x300?sig=50',
    price: 104,
    discounted: false,
    discount: 0,
    isPopular: false,
  },
]

export const Categories = [
  { id: 1, name: 'بخور' },
  { id: 2, name: 'عبايات' },
  { id: 3, name: 'حجابات' },
  { id: 4, name: 'نسائي' },
  { id: 5, name: 'اطفال' },
  { id: 6, name: 'بناتي' },
  { id: 7, name: 'رمضان,' },
  { id: 8, name: 'العيد' },
  { id: 9, name: 'افراح' },
  { id: 10, name: 'مناسبات' },
]

export const Colors = {
  black: '#2b2b2b',
  gray: '#dcdcdc',
  pink: '#ffeaed',
}
